development:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 5
  username: postgres
  password: 7989855
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5
  username: postgres
  password: 7989855
  timeout: 5000
